# Generated by Django 5.1.2 on 2024-10-30 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_item_alter_feeding_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='items',
            field=models.ManyToManyField(to='main_app.item'),
        ),
    ]
